name: Branch Build - Java Instrumentation Tests

on:
  push:
    branches-ignore:
      - '**WIP**'
      - 'main'
      - 'tcrone/fix-scala-gha-matrix-tests'

jobs:
  java-instrumentation-tests:
    uses: newrelic/newrelic-java-agent/.github/workflows/run-gradle-build.yml@main
    with:
      command: ./gradlew --console=plain :instrumentation:test -Ptest8 -PnoScala --continue
